-- Baseline schema for the Prent database.
--
-- Scope: the clinical-assistant data only. The appointments/scheduling + ER-queue
-- simulation subsystem (turnos, doctores, pacientes, asignaciones) was removed
-- end-to-end, so only the cost/usage tables remain: api_keys and chats.

-- updated_at maintenance trigger function (used by chats)
CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- API keys (cost/usage tracking)
CREATE TABLE IF NOT EXISTS public.api_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    organizacion character varying(100) NOT NULL,
    api_key character varying(255) NOT NULL UNIQUE,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    usage numeric(20,6) DEFAULT 0
);

-- Chat cost/token accounting (one row per conversation)
CREATE TABLE IF NOT EXISTS public.chats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id integer REFERENCES public.api_keys(id) ON DELETE SET NULL,
    messages_amount integer DEFAULT 0 NOT NULL CHECK (messages_amount >= 0),
    chat_cost numeric(10,4) DEFAULT 0 NOT NULL CHECK (chat_cost >= 0),
    total_tokens integer DEFAULT 0 NOT NULL CHECK (total_tokens >= 0),
    cache_tokens integer DEFAULT 0 NOT NULL CHECK (cache_tokens >= 0),
    input_tokens integer DEFAULT 0 NOT NULL CHECK (input_tokens >= 0),
    output_tokens integer DEFAULT 0 NOT NULL CHECK (output_tokens >= 0),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chats_created_at ON public.chats USING btree (created_at);

CREATE TRIGGER update_chats_updated_at
    BEFORE UPDATE ON public.chats
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to view chats" ON public.chats
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert chats" ON public.chats
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update chats" ON public.chats
    FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete chats" ON public.chats
    FOR DELETE USING (auth.role() = 'authenticated');
