-- Baseline schema for the Prent database.
--
-- Captured from the production database (restored locally via the downloaded
-- db_cluster backup, Postgres 17.4). This replaces the previous
-- create_chats_table.sql, which had drifted from reality: it declared
-- chats.paciente_id -> pacientes(id), but the real schema (and the app code in
-- db/utils.ts) use chats.api_key_id -> api_keys(id).

-- updated_at maintenance trigger function (used by chats)
CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- API keys (cost/usage tracking)
CREATE TABLE IF NOT EXISTS public.api_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    organizacion character varying(100) NOT NULL,
    api_key character varying(255) NOT NULL UNIQUE,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    usage numeric(20,6) DEFAULT 0
);

-- Doctors
CREATE TABLE IF NOT EXISTS public.doctores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    especialidad character varying(100) NOT NULL,
    ocupado boolean DEFAULT false NOT NULL
);

-- Patients (ER queue)
CREATE TABLE IF NOT EXISTS public.pacientes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    prioridad integer NOT NULL CHECK (prioridad >= 1 AND prioridad <= 5),
    hora_llegada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atendido boolean DEFAULT false NOT NULL,
    descripcion text
);
COMMENT ON COLUMN public.pacientes.descripcion IS 'afecciones del paciente';

-- Doctor <-> patient assignments
CREATE TABLE IF NOT EXISTS public.asignaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id integer NOT NULL REFERENCES public.doctores(id),
    paciente_id integer NOT NULL REFERENCES public.pacientes(id),
    hora_asignacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Appointments (scheduler "Claudia")
CREATE TABLE IF NOT EXISTS public.turnos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    paciente text,
    info text,
    date date NOT NULL,
    "time" time without time zone NOT NULL
);
COMMENT ON TABLE public.turnos IS 'Los turnos del Dr. Ejemplo';
COMMENT ON COLUMN public.turnos.date IS 'el dia del turno';
COMMENT ON COLUMN public.turnos."time" IS 'El horario de la consulta';
ALTER TABLE public.turnos ENABLE ROW LEVEL SECURITY;

-- Chat cost/token accounting (one row per conversation)
CREATE TABLE IF NOT EXISTS public.chats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id integer REFERENCES public.api_keys(id) ON DELETE SET NULL,
    messages_amount integer DEFAULT 0 NOT NULL CHECK (messages_amount >= 0),
    chat_cost numeric(10,4) DEFAULT 0 NOT NULL CHECK (chat_cost >= 0),
    total_tokens integer DEFAULT 0 NOT NULL CHECK (total_tokens >= 0),
    cache_tokens integer DEFAULT 0 NOT NULL CHECK (cache_tokens >= 0),
    input_tokens integer DEFAULT 0 NOT NULL CHECK (input_tokens >= 0),
    output_tokens integer DEFAULT 0 NOT NULL CHECK (output_tokens >= 0),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chats_created_at ON public.chats USING btree (created_at);

CREATE TRIGGER update_chats_updated_at
    BEFORE UPDATE ON public.chats
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to view chats" ON public.chats
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert chats" ON public.chats
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update chats" ON public.chats
    FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete chats" ON public.chats
    FOR DELETE USING (auth.role() = 'authenticated');
